@SCRUM-7 @AutoGenerated
Feature: Add to Cart from Search Results
  As a customer
  I want to search for a product and add it to my cart directly from the search results page
  So that I can quickly make purchases

  Background:
    Given I am on the Amazon homepage
    And I am logged in as a customer

  Scenario: Successfully adding a product to the cart from search results
    When I search for "wireless mouse"
    And I add the first product to my cart from the search results
    Then the cart should reflect the added item

  Scenario: Attempt to add a sold-out product to the cart
    When I search for "limited edition mouse"
    And I try to add the first product to my cart from the search results
    Then I should see "Product is sold out" message

  Scenario: Adding multiple products to the cart from search results
    When I search for "USB cable"
    And I add the first three products to my cart from the search results
    Then the cart should reflect three added items