@SCRUM-6 @AutoGenerated
Feature: User login with Two-Factor Authentication
  As a registered user
  I want to log in using two-factor authentication
  So that my account is more secure and protected against unauthorized access

  Background:
    Given I am on the login page

  Scenario: Successful login with 2FA
    When I enter "user@example.com" in the email field
    And I enter "ValidPass123!" in the password field
    And I click the login button
    And I enter the 2FA code received on my phone
    Then I should be redirected to the dashboard
    And I should see "Welcome back" message

  Scenario: Failed login with invalid 2FA code
    When I enter "user@example.com" in the email field
    And I enter "ValidPass123!" in the password field
    And I click the login button
    And I enter an incorrect 2FA code
    Then I should see an error message "Invalid 2FA code"
    And I should remain on the login page

  Scenario: Resend 2FA code
    When I enter "user@example.com" in the email field
    And I enter "ValidPass123!" in the password field
    And I click the login button
    And I click on "Resend Code" button
    Then I should receive a new 2FA code
    And I should be able to enter the new 2FA code