@SCRUM-1 @AutoGenerated
Feature: User login via email and password

  Background:
    Given I am on the login page

  Scenario: Successful login with valid credentials
    When I enter "user@example.com" in the email field
    And I enter "ValidPass123!" in the password field
    And I click the login button
    Then I should be redirected to the dashboard
    And I should see "Welcome back" message
    And a session token should be stored in cookies

  Scenario: Failed login with invalid email format
    When I enter "userexample.com" in the email field
    And I enter "ValidPass123!" in the password field
    And I click the login button
    Then I should see an error message "Please enter a valid email address"
    And I should remain on the login page

  Scenario: Failed login with invalid password
    When I enter "user@example.com" in the email field
    And I enter "short" in the password field
    And I click the login button
    Then I should see an error message "Password must be at least 8 characters long and include a mix of letters and numbers"
    And I should remain on the login page

  Scenario: Account locked after multiple failed login attempts
    Given I have entered incorrect credentials 3 times
    When I try to log in again with "user@example.com" and "ValidPass123!"
    Then I should see an error message "Your account has been locked due to multiple failed login attempts"
    And I should remain on the login page