@SCRUM-2 @AutoGenerated                                          
Feature: Refund Request from Order Details

  Background:
    Given the user is logged into their account
    And the user has navigated to the order details page

  Scenario: Request a refund for an eligible order
    Given the order was delivered within the last 30 days and payment was completed
    When the user selects a refund reason from the predefined list
    And the user submits the refund request
    Then the order status should be updated to "Refund Requested"
    And a confirmation email should be sent to the customer
    And an analytics event for "Refund Request Initiated" should be triggered

  Scenario: Attempt to request a refund for an ineligible order
    Given the order was delivered more than 30 days ago or payment was not completed
    When the user attempts to select a refund reason
    Then the refund option should not be visible
    And no refund request should be submitted

  Scenario: Request a refund without selecting a reason
    Given the order was delivered within the last 30 days and payment was completed
    When the user attempts to submit a refund request without selecting a reason
    Then the submission should be prevented
    And an error message "Please select a refund reason" should be displayed